### PR TITLE
Create an internal plugin infrastructure

### PR DESCRIPTION
**Pull request by pirelenito**
This PR is a WIP to create an internal *plugin infrastructure*. Once it is stable "enough" it could be exposed as an API to a project using Sagui.

The first internal (build) plugins are:

- Babel
- CSS Modules
- ESLint
- JSON
- Media: images and fonts
- Pages: support multiple page outputs
- SCSS

The internal plugin infrastructure is used to setup the entire Sagui environment, loading user preferences, setting up paths, the test runner (Karma) and the builder (Webpack).

It still requires some remaining cleaning work and documentation before it can be merged.

### CODE REVIEW

**Comment by xaviervia** [comment]
Looks neat. I guess the main question would be how to add a plugin to sagui, and where the plugin would reside.

**Comment by pirelenito** [comment]
So the idea is that a user can setup Sagui in two different ways:

### Configuration

By creating a file `sagui.config.js` you can leverage the existing plugins by providing some static configuration:

```js
module.exports = {
  pages: ['index', 'demo']
}
```

The configuration is **loaded before any plugin is processed**.

### Extension

Extension is a much powerful feature, by creating a file `sagui.extension.js`, the user has access to the entire runtime environment of Sagui, allowing extension of pretty much anything (such as webpack configuration). It works exactly like an internal plugin.

Here is an example of setting up an YAML loader:

```js
module.exports = function (env, merge) {
  const webpackConfig = merge(env.webpackConfig, {
    module: {
      loaders: [
        {
          test: /\.(yaml)$/,
          loader: 'yaml-loader'
        }
      ]
    }
  })

  return Object.assign({}, env, { webpackConfig: webpackConfig })
}
```

In contrast with configuration, the extension is executed as the **last step in the plugin chain**, allowing the user to overwrite or add any extra configuration.

**Comment by xaviervia** [comment]
:+1:

**Comment by pirelenito** [comment]
On the subject of plugins I think it is important that we don't try to come up with a complete new ecosystem. We already have Babel, ESLint and Webpack which are very modular libraries that can be extended as any project see fit. To open-up a project like Sagui as another plugin ecosystem would be just a terrible mistake that would make the community ever more confused.

So, the problem with these tools is that it can become overwhelmingly complicated to setup everything to get started. The good thing is that the community is already comming up with solutions that address this problem via Babel's [presets](http://babeljs.io/docs/plugins/) and ESLint's [config extension](http://eslint.org/docs/user-guide/configuring#extending-configuration-files) for example.

This is the point where I think Webpack is still lacking a good solution, a "presets" support to use and compose, and extend on a project by project base.

With that in mind, I'll try in a next iteration of this PR not to hide away these tools, but rather provide their native configuration methods while extending Sagui's defaults.

As the next steps of this PR, I'll toy around the idea of:
- A `sagui.webpack.config.js` that would work the same way as a regular webpack configuration file, but inheriting the default stuff from Sagui;
- Extract away Sagui's ESLint and Babel configuration as external packages.

We still have Karma, but I'll leave that for another moment.

**Pull request merged**
